// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {frontend} from '../models';

export function Greet(arg1:string):Promise<string>;

export function OpenDirectoryDialog(arg1:frontend.OpenDialogOptions):Promise<string>;

export function OpenMultipleFilesDialog(arg1:frontend.OpenDialogOptions):Promise<Array<string>>;
