// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function HandleAbout() {
  return window['go']['main']['App']['HandleAbout']();
}

export function HandleFileNew() {
  return window['go']['main']['App']['HandleFileNew']();
}

export function HandleFileOpen() {
  return window['go']['main']['App']['HandleFileOpen']();
}

export function HandlePreferences() {
  return window['go']['main']['App']['HandlePreferences']();
}

export function HandleQuit() {
  return window['go']['main']['App']['HandleQuit']();
}

export function OpenDirectoryDialog(arg1) {
  return window['go']['main']['App']['OpenDirectoryDialog'](arg1);
}

export function OpenMultipleFilesDialog(arg1) {
  return window['go']['main']['App']['OpenMultipleFilesDialog'](arg1);
}
